 #####################################################
##		         Plugin Revenge				         ##
##				   by Asynchronous					 ##
 #####################################################

#Enable melee mode and set the desired radius
#If enabled, when an animal starts his aggro on a player
#all entities in radius will attack the player (Skeletons, Zombies,... too).
melee-mode:
  enable: false
  radius: 20.0
  
#Particle to show when a mob fight a player.
#Put 'null' to show no particles.
#Go here to customize particles: https://roytreo28.github.io/Revenge/particle-selector/
hit-particles: 'CRIT;3;0.1;0.5;0.3;0.5;0'

tracked-info:
  #If enabled, the head of the player aggro by the animal will be displayed above it.
  enable: true
  #Description is the message displayed above the head.
  description: "&bI want to kill %PLAYER%"

#Allows animals to have more "realistic" movements and behavior.
random-behavior: true

#Allows animals to bleed.
animals-blood: false

#Disable worlds
disable-worlds:
  - 'example'
 
#Configured mobs list
moblist:
  BAT:
    #Enable or not the mob aggro
    enable: true
    #The name of the mob (used for %NAME% in death-message)
    name: 'Bat'
    #Speed of the mob during aggro
    speed: 1.0
    #Damage dealt by the mob during aggro
    damage: 2.0
    #Damage interval mean how many second to wait between each hit (put 0 to disable this feature)
    damage-interval: 0
    #From how many blocks the mob can hit you
    hit-radius: 2.5
    #Percent means the luck to aggro this mob when hitting it
    percent: 50
    #Stop aggro after how many seconds ? (put 0 to disable this feature)
    stop-time: 60
    #Stop aggro if player is how many blocks far away the mob ? (put 0 to disable this feature)
    stop-blocks: 20
    #Death message when the player is killed by this mob
    death-message: '%PLAYER% was killed by %NAME%'
  CHICKEN:
    enable: true
    name: 'Chicken'
    speed: 1.0
    damage: 2.0
    damage-interval: 0
    hit-radius: 2.5
    percent: 50
    stop-time: 60
    stop-blocks: 20
    death-message: '%PLAYER% was killed by %NAME%'
  COW:
    enable: true
    name: 'Cow'
    speed: 1.0
    damage: 2.0
    damage-interval: 0
    hit-radius: 2.5
    percent: 50
    stop-time: 60
    stop-blocks: 20
    death-message: '%PLAYER% was killed by %NAME%'
  MUSHROOM_COW:
    enable: true
    name: 'Mushroom Cow'
    speed: 1.0
    damage: 2.0
    damage-interval: 0
    hit-radius: 2.5
    percent: 50
    stop-time: 60
    stop-blocks: 20
    death-message: '%PLAYER% was killed by %NAME%'
  PIG:
    enable: true
    name: 'Pig'
    speed: 1.0
    damage: 2.0
    damage-interval: 0
    hit-radius: 2.5
    percent: 50
    stop-time: 60
    stop-blocks: 20
    death-message: '%PLAYER% was killed by %NAME%'
  SHEEP:
    enable: true
    name: 'Sheep'
    speed: 1.0
    damage: 2.0
    damage-interval: 0
    hit-radius: 2.5
    percent: 50
    stop-time: 60
    stop-blocks: 20
    death-message: '%PLAYER% was killed by %NAME%'
  SQUID:
    enable: true
    name: 'Squid'
    speed: 1.0
    damage: 2.0
    damage-interval: 0
    hit-radius: 2.5
    percent: 50
    stop-time: 60
    stop-blocks: 20
    death-message: '%PLAYER% was killed by %NAME%'
  HORSE:
    enable: true
    name: 'Horse'
    speed: 1.0
    damage: 2.0
    damage-interval: 0
    hit-radius: 2.5
    percent: 50
    stop-time: 60
    stop-blocks: 20
    death-message: '%PLAYER% was killed by %NAME%'
  VILLAGER:
    enable: true
    name: 'Villager'
    speed: 1.0
    damage: 2.0
    damage-interval: 0
    hit-radius: 2.5
    percent: 50
    stop-time: 60
    stop-blocks: 20
    death-message: '%PLAYER% was killed by %NAME%'
  WOLF:
    enable: false
    name: 'Wolf'
    speed: 1.0
    damage: 2.0
    damage-interval: 0
    hit-radius: 2.5
    percent: 50
    stop-time: 60
    stop-blocks: 20
    death-message: '%PLAYER% was killed by %NAME%'
  OCELOT:
    enable: true
    name: 'Little Kitty'
    speed: 1.0
    damage: 2.0
    damage-interval: 0
    hit-radius: 2.5
    percent: 50
    stop-time: 60
    stop-blocks: 20
    death-message: '%PLAYER% was killed by %NAME%'
#Enable Rabbit and Polar Bears if you server is in 1.8 or higher for Rabbit
#and in 1.10 or higher for Polar Bears. To tell to the plugin to take account
#of them, remove '#' before each attributes.
#If you have any issue, please contact the developer.
#  RABBIT:
#    enable: true
#    name: 'Rabbit'
#    speed: 1.0
#    damage: 2.0
#    damage-interval: 0
#    hit-radius: 2.5
#    percent: 50
#    stop-time: 60
#    stop-blocks: 20
#    death-message: '%PLAYER% was killed by %NAME%'
#  POLAR_BEAR:
#    enable: true
#    name: 'Polar Bear'
#    speed: 1.0
#    damage: 2.0
#    damage-interval: 0
#    hit-radius: 2.5
#    percent: 50
#    stop-time: 60
#    stop-blocks: 20
#    death-message: '%PLAYER% was killed by %NAME%'